### PR TITLE
Start and Stop workflows

### PR DESCRIPTION
**Pull request by GrantBirki**
This pull request adds two new workflows that can be run by members of this repository with `write` permissions. These workflows are available from the `actions` tab on GitHub and allow for users to **start** or **stop** the tarkov-data-manager (TDM) VM. It should be noted that the `stop` workflow can take up to 10 minutes to actually complete. If the stop workflow completes in less than 1 minute, it is probably a lie. You should check the [status page](https://status.tarkov.dev/status/the-hideout) or try to manually access the VM (either via ssh or the web UI) to actually confirm if it has stopped or not.

On the flip side, the `start` workflow should only take a minute or two to fully boot the VM back up.

cc: @Razzmatazzz

### CODE REVIEW

**Review by Razzmatazzz — APPROVED** [review]

**Comment by GrantBirki** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.unlock production

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Pull request merged**
