### PR TITLE
use jimp-compact to remove vuln

### PR DESCRIPTION
**Pull request by GrantBirki**
resolves: https://github.com/the-hideout/tarkov-data-manager/security/dependabot/4

### CODE REVIEW

**Comment by GrantBirki** [comment]
.deploy

**Comment by GrantBirki** [comment]
.deploy main

**Comment by GrantBirki** [comment]
.deploy main

**Comment by GrantBirki** [comment]
.deploy

**Review by Razzmatazzz — APPROVED** [review]

**Pull request merged**
