### PR TITLE
update dependencies

### PR DESCRIPTION
**Pull request by Razzmatazzz**
Update dependencies.

### CODE REVIEW

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Review by GrantBirki — APPROVED** [review]
⭐

**Pull request merged**
