### PR TITLE
Better presets

### PR DESCRIPTION
**Pull request by Razzmatazzz**
Adds data for defaultPreset field on ItemPropertiesWeapon.

Also ensures default weapon presets are added as their own items.

Simplifies storage of preset parts by bypassing the DB.

### CODE REVIEW

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Review by GrantBirki — DISMISSED** [review]

**Comment by Razzmatazzz** [comment]
.deploy

**Review by GrantBirki — APPROVED** [review]

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Review by GrantBirki — APPROVED** [review]

**Pull request merged**
