### PR TITLE
Task failure info

### PR DESCRIPTION
**Pull request by Razzmatazzz**
Fixes an issue with barter reward attributes and provides task failure info for the API. 

Resolves the-hideout/tarkov-api#154
Resolves the-hideout/tarkov-api#125
Resolves the-hideout/tarkov-api#122

### CODE REVIEW

**Review by Shebuka — APPROVED** [review]

**Comment by Razzmatazzz** [comment]
.deploy

**Review by GrantBirki — APPROVED** [review]

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Review by GrantBirki — APPROVED** [review]

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Review by Shebuka — APPROVED** [review]

**Pull request merged**
