### PR TITLE
convert to es modules

### PR DESCRIPTION
**Pull request by Razzmatazzz**
This seems to work in limited local testing. We should deploy and watch closely.

Also removes Sentry because nobody seems sure of whether we're using it any longer and removing means fewer packages to update.

### CODE REVIEW

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy main

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy main

**Comment by GrantBirki** [comment]
.unlock production

**Comment by GrantBirki** [comment]
.deploy

**Comment by GrantBirki** [comment]
.deploy main

**Comment by GrantBirki** [comment]
.deploy main

**Comment by GrantBirki** [comment]
.deploy

**Comment by GrantBirki** [comment]
.deploy main

**Comment by GrantBirki** [comment]
.deploy

**Comment by GrantBirki** [comment]
.deploy

**Comment by GrantBirki** [comment]
.unlock

**Comment by Razzmatazzz** [comment]
.deploy

**Review by Blightbuster — APPROVED** [review]

**Pull request merged**
