### PR TITLE
Allow manual translations for guard names

### PR DESCRIPTION
**Pull request by Razzmatazzz**
If a translation is missing, it defaults to the kludge of `[bossName] [Guard] ([GuardType])`.

### CODE REVIEW

**Review by Shebuka — APPROVED** [review]

**Comment by Shebuka** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Review by Shebuka — APPROVED** [review]

**Review by GrantBirki — APPROVED** [review]

**Pull request merged**
