### PR TITLE
Handbook categories

### PR DESCRIPTION
**Pull request by Razzmatazzz**
Adds handbookCategories attribute to Item.

### CODE REVIEW

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Review by Shebuka — APPROVED** [review]

**Review by GrantBirki — DISMISSED** [review]

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Review by Shebuka — DISMISSED** [review]

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Review by GrantBirki — APPROVED** [review]

**Review by Shebuka — APPROVED** [review]

**Pull request merged**
