### PR TITLE
Fix quest requirements

### PR DESCRIPTION
**Pull request by Razzmatazzz**
- Swift One
- Chemistry Closet
- Stirrup
- Colleagues - Part 3
- Make an Impression
- Crisis
- Hunter
- Provocation
- The Cleaner
- Payback

### CODE REVIEW

**Review by Shebuka — APPROVED** [review]

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Review by GrantBirki — DISMISSED** [review]

**Review by GrantBirki — APPROVED** [review]

**Comment by GrantBirki** [comment]
This has been deployed for almost a day so I will merge for ya!

**Pull request merged**
