### PR TITLE
Work with fewer db indexes

### PR DESCRIPTION
**Pull request by Razzmatazzz**
This should be deployed when the ferwer-indexes planetscale branch is deployed. Then testing should be done to ensure things are working properly during the planetscale rollback window. If not working and unable to fix within the db undo window, the db deploy should be reversed and we should `.deploy main` here.

### CODE REVIEW

**Comment by GrantBirki** [comment]
Approved here and in PlanetScale as well

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Review by Shebuka — APPROVED** [review]

**Pull request merged**
