### PR TITLE
add s3 bucket manager

### PR DESCRIPTION
**Pull request by Razzmatazzz**
Adds an S3 Bucket page that lists all the files in our S3 bucket, and includes the ability to add and delete items.

Also adds trader images.

### CODE REVIEW

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.lock one deploy at a time

**Comment by Razzmatazzz** [comment]
.lock --reason one deploy at a time

**Comment by Razzmatazzz** [comment]
.lock --reason please approve and merge #196 first

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Review by GrantBirki — APPROVED** [review]

**Comment by Razzmatazzz** [comment]
.unlock

**Pull request merged**
