### PR TITLE
add sniper category to spawns

### PR DESCRIPTION
**Pull request by Razzmatazzz**
Adds "sniper" to the category property for sniper scav spawns.
Add Test Drive - Part 4
Get objective location(s) from the type of enemy to be killed

### CODE REVIEW

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Review by GrantBirki — APPROVED** [review]

**Pull request merged**
