### PR TITLE
fix sell prices for real

### PR DESCRIPTION
**Pull request by Razzmatazzz**

### CODE REVIEW

**Comment by Razzmatazzz** [comment]
.deploy

**Review by austinhodak — DISMISSED** [review]

**Comment by Razzmatazzz** [comment]
.deploy

**Review by GrantBirki — APPROVED** [review]

**Comment by GrantBirki** [comment]
.deploy

**Comment by GrantBirki** [comment]
.deploy

**Comment by GrantBirki** [comment]
.unlock

**Comment by GrantBirki** [comment]
.deploy

**Review by GrantBirki — APPROVED** [review]

**Pull request merged**
