### PR TITLE
Unpack ammo barters

### PR DESCRIPTION
**Pull request by Razzmatazzz**
Barters that provide ammo boxes are now duplicated to also provide barters for the correct amount of ammo contained in the ammo boxes. This helps evaluate the value of these barters.

Resolves the-hideout/tarkov-api/issues/178

### CODE REVIEW

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Review by GrantBirki — APPROVED** [review]

**Pull request merged**
