### PR TITLE
Fix job scheduling error

### PR DESCRIPTION
**Pull request by Razzmatazzz**
Fix error for trying to schedule a job with a custom cron when that job no longer exists.

### CODE REVIEW

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Review by Shebuka — APPROVED** [review]

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Pull request merged**
