### PR TITLE
Add Queue API

### PR DESCRIPTION
**Pull request by GrantBirki**
# Queue API 💻 

This pull request implements a new API endpoint for crowd-sourced queue time data for Escape from Tarkov

- API endpoint: `/api/queue`

## How does it work? 💡 

Data is submitted to the endpoint in the following fashion:

- POST to `/api/queue`

Body:

```json
{
	"map": "factory",
	"time": 80
}
```

Where `map` is the map name and `time` is the time to queue in seconds

> Note: In the future, we can try and tell the difference between `scav` and `pmc` raids and also submit the `type: <string>` value in this body payload

---

Upon submitting this POST request, the TDM stores the record in the PlanetScale database with the current timestamp

At a set interval, the `update-queue-times` cron job (in the TDM) is kicked off which searches all events in the database sorted by time (times seen below). These times are then averaged for each map and the resulting JSON structure is placed into the cloudflare KV store

## Examples 📸 

Example JSON data structure:

> The JSON payload seen below is what will be stored in the cloudflare KV at the set cron interval

Each value below is sorted by the timestamp of events parsed in this order:

- Last 1 hour
- Last 6 hours
- Last 12 hours
- Last 1 day
- Last 7 days

```json
{
    "last 1 hour": {
        "queueData": [
            {
                "map": "customs",
                "time": 203
            },
            {
                "map": "factory",
                "time": 115
            },
            {
                "map": "night factory",
                "time": 51
            },
            {
                "map": "interchange",
                "time": 384
            },
            {
                "map": "lighthouse",
                "time": 341
            },
            {
                "map": "reserve",
                "time": 99
            },
            {
                "map": "shoreline",
                "time": 488
            },
            {
                "map": "the lab",
                "time": 113
            },
            {
                "map": "woods",
                "time": 73
            }
        ],
        "timestamp": "2022-07-16 10: 12: 43"
    },
    "last 6 hours": {
        "queueData": [
            {
                "map": "customs",
                "time": 203
            },
            {
                "map": "factory",
                "time": 111
            },
            {
                "map": "night factory",
                "time": 51
            },
            {
                "map": "interchange",
                "time": 384
            },
            {
                "map": "lighthouse",
                "time": 341
            },
            {
                "map": "reserve",
                "time": 99
            },
            {
                "map": "shoreline",
                "time": 488
            },
            {
                "map": "the lab",
                "time": 113
            },
            {
                "map": "woods",
                "time": 73
            }
        ],
        "timestamp": "2022-07-16 05:12:43"
    },
    "last 12 hours": {
        "queueData": [
            {
                "map": "customs",
                "time": 203
            },
            {
                "map": "factory",
                "time": 98
            },
            {
                "map": "night factory",
                "time": 51
            },
            {
                "map": "interchange",
                "time": 384
            },
            {
                "map": "lighthouse",
                "time": 341
            },
            {
                "map": "reserve",
                "time": 99
            },
            {
                "map": "shoreline",
                "time": 488
            },
            {
                "map": "the lab",
                "time": 113
            },
            {
                "map": "woods",
                "time": 73
            }
        ],
        "timestamp": "2022-07-15 23: 12: 43"
    },
    "last 1 day": {
        "queueData": [
            {
                "map": "customs",
                "time": 203
            },
            {
                "map": "factory",
                "time": 98
            },
            {
                "map": "night factory",
                "time": 51
            },
            {
                "map": "interchange",
                "time": 384
            },
            {
                "map": "lighthouse",
                "time": 341
            },
            {
                "map": "reserve",
                "time": 99
            },
            {
                "map": "shoreline",
                "time": 488
            },
            {
                "map": "the lab",
                "time": 113
            },
            {
                "map": "woods",
                "time": 73
            }
        ],
        "timestamp": "2022-07-15 11:12:43"
    },
    "last 7 days": {
        "queueData": [
            {
                "map": "customs",
                "time": 203
            },
            {
                "map": "factory",
                "time": 98
            },
            {
                "map": "night factory",
                "time": 51
            },
            {
                "map": "interchange",
                "time": 384
            },
            {
                "map": "lighthouse",
                "time": 341
            },
            {
                "map": "reserve",
                "time": 99
            },
            {
                "map": "shoreline",
                "time": 488
            },
            {
                "map": "the lab",
                "time": 113
            },
            {
                "map": "woods",
                "time": 73
            }
        ],
        "timestamp": "2022-07-09 11: 12: 43"
    }
}
```

### CODE REVIEW

**Comment by GrantBirki** [comment]
@Razzmatazzz what I need help with 👀 

- Properly adding this JSON payload to the cloudflare KV store -> https://github.com/the-hideout/tarkov-data-manager/pull/98/files#diff-742d7748d5d61c55c7a42ccb8ac7df25f49374b8f89a74589c4de3394c9e7b55R88-R89
- A peer review of all the code to ensure none of my changes will break anything
- Any feedback or suggestions to make the code cleaner / improvements
- Thoughts on improving the "key" returned via the graphql API for clients to consume this data. Right now, the "key" is the raw timestamp. A "friendly" name like, "last 6 hours" might be better

**Comment by Razzmatazzz** [comment]
Looking at this now.  One preliminary question I had is what's the rationale behind ignoring night factory as a separate map? While most people may think of it as "Factory, but at night," it actually is a distinct map as far as the game is concerned (which possibly means different queue times). Plus, if we tie the queue times to actual maps, the API can return the Map type instead of just a lowercase map name.

**Comment by Razzmatazzz** [comment]
Also, what are your thoughts on making the queue time data be accessible from the Map type instead of its own query?

**Comment by GrantBirki** [comment]
> One preliminary question I had is what's the rationale behind ignoring night factory as a separate map?

This is certainly a flaw in my logic. We should not exclude factory night as a map. I'll fix this 😄 

> Also, what are your thoughts on making the queue time data be accessible from the Map type instead of its own query?

I think this would be a great idea! How would we go about adding this data to the Map type in the current API structure?

**Comment by Razzmatazzz** [comment]
I started some edits, but I'm currently in the middle of a soldering project.

**Comment by GrantBirki** [comment]
Made some commits and submitted some mock data to the database for us to experiment with:

image

**Comment by GrantBirki** [comment]
Updated the JSON structure see in the original comment

**Comment by Razzmatazzz** [comment]
I just pushed some changes that put the queue data in the maps data. I don't think the cutoffs are working properly, though, and I'm sick of troubleshooting it.

**Comment by Razzmatazzz** [comment]
With my changes, the update-queue-times job isn't used anymore. Instead, the map-queue-times module is called by the update-maps job to get the map queue times as part of the map data.

**Review by Razzmatazzz — APPROVED** [review]

**Pull request merged**
