### PR TITLE
Update tarkov-spt.js

### PR DESCRIPTION
**Pull request by Razzmatazzz**
Fix SPT

### CODE REVIEW

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Review by GrantBirki — APPROVED** [review]

**Review by Shebuka — APPROVED** [review]

**Pull request merged**
