### PR TITLE
Task actual min player level

### PR DESCRIPTION
**Pull request by Razzmatazzz**
Ensures minPlayerLevel on tasks is actually the minimum level required to start the task based on prerequisites.

### CODE REVIEW

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Review by GrantBirki — DISMISSED** [review]

**Review by Shebuka — APPROVED** [review]

**Comment by Razzmatazzz** [comment]
.deploy

**Review by Shebuka — APPROVED** [review]

**Pull request merged**
