### PR TITLE
bump img gen

### PR DESCRIPTION
**Pull request by Razzmatazzz**

### CODE REVIEW

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Review by Shebuka — APPROVED** [review]

**Comment by Shebuka** [comment]
After we deployed this change, this is what I see again on loot tier page

Screenshot 2022-09-29 at 17 34 24

definetely something goingo on with presets or caching

**Comment by Shebuka** [comment]
> After we deployed this change, this is what I see again on loot tier page
> 
> Screenshot 2022-09-29 at 17 34 24
> 
> definetely something goingo on with presets or caching

And now it's back normal:

Screenshot 2022-09-29 at 17 38 35

**Comment by Razzmatazzz** [comment]
This PR didn't change anything about weapon sizes. On the website PR dev deployment, it looks like it cached incorrect item weapon sizes for some reason and the sizes would be corrected when the "fresh" data loads in. That's not happening when I run the website locally, so probably a weird error when the cache was being build on the dev deployment.

**Comment by Shebuka** [comment]
> This PR didn't change anything about weapon sizes. On the website PR dev deployment, it looks like it cached incorrect item weapon sizes for some reason and the sizes would be corrected when the "fresh" data loads in. That's not happening when I run the website locally, so probably a weird error when the cache was being build on the dev deployment.

I know this is not related to this PR, but we have seen this behaviour already in the past when developing other features. This is just a reminder that we still have this issue somewhere.

**Pull request merged**
