### PR TITLE
Quest item images

### PR DESCRIPTION
**Pull request by Razzmatazzz**
Add descriptions to items and images to quest items.

### CODE REVIEW

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Review by Shebuka — DISMISSED** [review]

**Review by Shebuka — DISMISSED** [review]

**Comment by Razzmatazzz** [comment]
.deploy

**Review by Shebuka — APPROVED** [review]

**Pull request merged**
