### PR TITLE
Update quests

### PR DESCRIPTION
**Pull request by Razzmatazzz**

### CODE REVIEW

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy main

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by GrantBirki** [comment]
.lock

**Comment by GrantBirki** [comment]
.deploy noop

**Comment by GrantBirki** [comment]
.deploy

**Comment by GrantBirki** [comment]
.unlock

**Review by GrantBirki — APPROVED** [review]

**Pull request merged**
