### PR TITLE
Update presets

### PR DESCRIPTION
**Pull request by Razzmatazzz**

### CODE REVIEW

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Review by Shebuka — APPROVED** [review]

**Review by Shebuka — APPROVED** [review]

**Comment by Shebuka** [comment]
Do we have the translations for Kollontay boss name?

**Review by GrantBirki — APPROVED** [review]
✨ ⭐ ✨

**Comment by Razzmatazzz** [comment]
> Do we have the translations for Kollontay boss name?

It's not in the game's translation files, which is why I added it to the manual translations english file in this repo.

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Pull request merged**
