### PR TITLE
Include offer count in archived prices

### PR DESCRIPTION
**Pull request by Razzmatazzz**
The job to archive detailed prices now also reads offer counts from historical prices and includes those in the archived price data. Removing old historical prices is also moved from the historical prices job to the archive prices job.

### CODE REVIEW

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Review by GrantBirki — APPROVED** [review]

**Review by Shebuka — APPROVED** [review]

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Review by Shebuka — APPROVED** [review]

**Review by GrantBirki — APPROVED** [review]

**Pull request merged**
