### PR TITLE
Added tool type attribute to update crafts from wiki 

### PR DESCRIPTION
**Pull request by Shebuka**

### CODE REVIEW

**Comment by Shebuka** [comment]
Btw, is the `update-crafts-wiki.js` used anymore?

**Review by GrantBirki — APPROVED** [review]
🎉

**Comment by GrantBirki** [comment]
.deploy

**Comment by GrantBirki** [comment]
.deploy

**Comment by GrantBirki** [comment]
.deploy

**Comment by GrantBirki** [comment]
.deploy noop

**Comment by GrantBirki** [comment]
Sorry for all the noise on your PR @Shebuka. You are one of our first public contributors and we are using a relatively new GitHub Action workflow that has not been tested on repository forks yet. You are the first and we are attempting to iron out all the bugs! 🐛

**Comment by GrantBirki** [comment]
.deploy

**Comment by GrantBirki** [comment]
@Shebuka I have released a new version of the public Action that powers deployments for most of this organization -> https://github.com/github/branch-deploy/releases/tag/v2.0.1

This latest release should fix this issue with deployments

**Comment by GrantBirki** [comment]
.deploy

**Comment by GrantBirki** [comment]
.deploy

**Comment by GrantBirki** [comment]
.deploy

**Comment by GrantBirki** [comment]
.deploy

**Comment by GrantBirki** [comment]
.deploy

**Comment by GrantBirki** [comment]
.deploy noop

**Comment by GrantBirki** [comment]
.deploy

**Comment by GrantBirki** [comment]
.deploy

**Comment by GrantBirki** [comment]
.deploy

**Comment by GrantBirki** [comment]
.deploy main

**Comment by GrantBirki** [comment]
.deploy

**Comment by GrantBirki** [comment]
.deploy

**Comment by GrantBirki** [comment]
@Razzmatazzz and @Shebuka sorry for the tons of noise on this PR. I used this PR to troubleshoot and release a new version of the Action that powers our branch deployments and it now works with contributors! Your PR (this one) has been deployed to production. If all looks good, a member of @the-hideout/core-contributors will merge this PR

**Comment by Razzmatazzz** [comment]
.deploy

**Pull request merged**
