### PR TITLE
centralize limits on maximum query rows

### PR DESCRIPTION
**Pull request by Razzmatazzz**
Due to limitations in previous DB provider, we had to limit queries to affecting a maximum of 100,000 rows at a time. For queries that would be expected to deal with more rows than this, they were batched out in groups of 100,000. This PR centralizes the row limit to a single variable. Because our current DB doesn't have the same limitation, this PR also sets the limit to the maximum integer value, essentially removing it.

### CODE REVIEW

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy main

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.unlock production

**Comment by Razzmatazzz** [comment]
.unlock production

**Comment by GrantBirki** [comment]
Whoa that is weird

**Comment by GrantBirki** [comment]
.unlock

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Review by GrantBirki — APPROVED** [review]

**Pull request merged**
