### PR TITLE
Event jobs

### PR DESCRIPTION
**Pull request by Razzmatazzz**
Allows running jobs based on events in addition to on a specific cron schedule.

Useful for things like trader prices where scanning concludes at unpredictable times.

### CODE REVIEW

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Comment by Razzmatazzz** [comment]
.deploy

**Review by GrantBirki — APPROVED** [review]
I see a PR by razz and I press approve

**Pull request merged**
